apiVersion: apps/v1
kind: Deployment
metadata:
  name: campus-backend
  labels:
    app: campus-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: campus-backend
  template:
    metadata:
      labels:
        app: campus-backend
    spec:
      containers:
        - name: backend
          image: campus-network-monitor-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
